### PR TITLE
Added MacOS and Linux Oink binaries

### PR DESCRIPTION
**Pull request by petejaustin**
This pull would add the ELF and Mach-O binaries to the dist-template-tools. This pull would be necessary for my Parity Game Plugin to work; I have noted in my PR for Workcraft that the .gitmodules text file would need to be changed back to workcraft/workcraft-dist-template from petejaustin/workcraft-dist-template if this is accepted.

### CODE REVIEW

**Comment by danilovesky** [comment]
Thank you for this contribution!

A couple of requests:
1. Could you statically link `oink` binary (both in Linux and OSX), so it does not depend on dynamic libraries? I am asking because I tried running it in a couple of Linux virtual machines and both had some dependencies missing. Not everybody has rights or skills to install necessary libraries.
2. Could you strip `oink` of symbols? This is to reduce the binary size. I tried `$ strip oink` in Linux and its size was reduced from 2.8M to 1.4M.

Please have a look at https://workcraft.org/devel/backend/start for some examples of how we build backend tools to make sure they run reliably on a wide range of distributions. I am happy to help too.

**Comment by petejaustin** [comment]
Thank you for the feedback!
I will go ahead and perform those requests. I apologise for not having addressed that issue immediately.

**Comment by petejaustin** [comment]
I have been considering the utility of Oink over the weekend, and I have been able to implement my own backend without needing to use Oink at all. This also means that there are no longer any limitations on the OS the parity plugin can run on either!

**Comment by danilovesky** [comment]
Do you mean you have implemented everything directly in Java, without the need for a dedicated binary backend tool?
If so, we probably can keep `workcraft-dist-template` submodule untouched, right?
And `.gitmodules` file can probably be reverted too...

**Comment by petejaustin** [comment]
That is exactly what I mean. And yes you are correct, workcraft-dist-template can remain untouched.
I do think I forgot to revert .gitmodules back to what it was, sorry. I can change that if you like?

**Comment by danilovesky** [comment]
Great! Let us move discussion into the main PR in `workcraft` repo (I have a couple of minor comments/suggestions there).

**Pull request closed without merging**
